"""Byte equality is visible without collapsing received source occurrences."""
import re

import pytest

from tests.test_intake_receipt_http import ACTOR, descriptor, selection, upload, put, workspace  # noqa: F401
from tests.test_upload_occurrences import _settled


def matched_sources(client, bench, matter, paths=None):
    bodies = [b'Generated matching received passage.\n',
        b'Generated matching received passage.\n', b'Generated different received passage.\n']
    records = []
    for index, body in enumerate(bodies):
        files = [descriptor(paths[index] if paths else 'Records/report.txt', len(body))]
        title = f'Generated byte comparison collection {index + 1}'
        receipt = selection(client, matter.slug, files, [0], key=str(index + 1) * 32, title=title)
        session = upload(client, matter.slug, receipt, files, [0], collection_name=title)
        put(client, session['items'][0], body)
        assert client.post(session['items'][0]['finalize_url']).status_code == 200
        _settled(bench, matter)
        library = bench.source_library(matter, collection_id=session['collection_id'])
        assert library.total == 1
        records.append(bench.source_store(matter).get(library.items[0].document_id))
    return records


@pytest.mark.parametrize("paths", [None, ("North/a.txt", "South/b.txt", "Other/c.txt")])
def test_sources_open_exact_byte_matches_across_occurrences_without_exposing_hashes(workspace, paths):
    client, bench, matter = workspace
    documents = matched_sources(client, bench, matter, paths)
    assert len({d.document_id for d in documents}) == 3
    assert documents[0].digest == documents[1].digest != documents[2].digest
    page = client.get(f'/matters/{matter.slug}/setup?view=list')
    links = re.findall(r'href="([^"]+)"[^>]*data-source-byte-matches', page.text)
    assert len(links) == 2
    assert all(d.digest not in page.text for d in documents)
    from html import unescape
    compared = client.get(unescape(links[0]))
    assert compared.status_code == 200 and compared.text.count('class="source-table-row') == 2
    assert 'Generated byte comparison collection 1' in compared.text
    assert 'Generated byte comparison collection 2' in compared.text
    cells = re.findall(r'<span class="source-collection-cell".*?</span>', compared.text, re.S)
    assert 'Generated byte comparison collection 3' not in ''.join(cells)
    assert all(d.digest not in compared.text for d in documents)
    for document in documents[:2]:
        token = bench.source_store(matter).action_token(document)
        source = client.get(f'/matters/{matter.slug}/sources/{token}')
        assert source.status_code == 200 and 'Generated matching received passage.' in source.text
    assert len(bench.source_store(matter).documents) == 3


def test_a_missing_comparison_reference_never_broadens_the_source_view(workspace):
    client, bench, matter = workspace
    documents = matched_sources(client, bench, matter)
    page = client.get(f'/matters/{matter.slug}/setup', params={'view': 'list', 'same_content': 'f' * 32})
    assert page.status_code == 200 and page.text.count('class="source-table-row') == 0
    assert 'comparison is unavailable' in page.text
    token = bench.source_store(matter).action_token(documents[0])
    assert client.post(f'/matters/{matter.slug}/sources/{token}/remove').status_code == 200
    page = client.get(f'/matters/{matter.slug}/setup', params={'view': 'list', 'same_content': token})
    assert page.status_code == 200 and page.text.count('class="source-table-row') == 0
    assert 'comparison is unavailable' in page.text


def test_foreign_comparison_and_malformed_token_never_disclose_or_broaden(workspace):
    client, bench, matter = workspace
    documents = matched_sources(client, bench, matter)
    foreign = bench.create_matter('Generated foreign comparison', '', 'development-jordan-lee')
    store = bench.source_store(foreign)
    body = b'Generated matching received passage.\n'
    item = 'upload-item-' + 'e' * 32
    store.append_resumable_chunk(item, offset=0, expected_size=len(body), chunk=body)
    other = store.finalize_resumable_upload(item, display_name='report.txt',
        relative_path='Records/report.txt', content_type='text/plain', expected_size=len(body))
    foreign_token = store.action_token(other)
    page = client.get(f'/matters/{matter.slug}/setup', params={'same_content': foreign_token})
    assert page.status_code == 200 and not re.findall('class="source-table-row', page.text)
    assert 'comparison is unavailable' in page.text and 'Generated foreign comparison' not in page.text
    assert client.get(f'/matters/{foreign.slug}/setup', params={
        'same_content': bench.source_store(matter).action_token(documents[0])}).status_code == 404
    for malformed in ('bad', 'g' * 32, "'" * 32):
        assert client.get(f'/matters/{matter.slug}/setup', params={'same_content': malformed}).status_code == 400


def test_unknown_changed_missing_and_version_changes_remove_matches(workspace):
    client, bench, matter = workspace
    documents = matched_sources(client, bench, matter)
    store = bench.source_store(matter)
    reference = documents[0]
    token = store.action_token(reference)
    for state in ('changed', 'missing', 'quarantined', 'unknown'):
        with store._lock:
            reference.state = state
            store._save([reference.document_id])
        assert bench.source_library(matter, matching_only=True).total == 0
        assert bench.source_library(matter, same_content=token).total == 0
    with store._lock:
        reference.state = 'ready'
        reference.version_id = 'a' * 32
        reference.digest = documents[2].digest
        reference.size = documents[2].size
        store._save([reference.document_id])
    assert bench.source_library(matter, same_content=token).total == 0
    current = bench.source_library(matter, same_content=store.action_token(reference))
    assert {s.document_id for s in current.items} == {reference.document_id, documents[2].document_id}
    assert all(s.byte_match_count == 2 for s in current.items)
    with store._lock:
        reference.digest = ''
        store._save([reference.document_id])
    assert bench.source_library(matter, matching_only=True).total == 0


def test_comparison_filters_and_folder_navigation_preserve_scope(workspace):
    from html import unescape
    from urllib.parse import parse_qs, urlsplit
    client, bench, matter = workspace
    documents = matched_sources(client, bench, matter)
    token = bench.source_store(matter).action_token(documents[0])
    page = client.get(f'/matters/{matter.slug}/setup', params={
        'same_content': token, 'matching_only': 'true', 'view': 'list'})
    assert page.text.count('class="source-table-row') == 2
    assert f'name="same_content" value="{token}"' in page.text
    nav = re.search(r'<nav[^>]*data-source-folder-nav.*?</nav>', page.text, re.S).group(0)
    for link in re.findall('href="([^"]+)"', nav):
        query = parse_qs(urlsplit(unescape(link)).query)
        assert query['same_content'] == [token] and query['matching_only'] == ['true']
        viewed = client.get(unescape(link))
        assert viewed.status_code == 200 and viewed.text.count('class="source-table-row') == 2
    collection = bench.source_library(matter).items[0].collection_id
    scoped = bench.source_library(matter, same_content=token, collection_id=collection)
    assert scoped.total == 0  # newest collection contains the different bytes


@pytest.mark.parametrize("filter_mode", ["all", "matching", "comparison"])
def test_byte_match_catalog_is_bounded_and_rebuildable_at_ten_thousand_sources(tmp_path, filter_mode):
    from fastapi.testclient import TestClient
    from case_intelligence.generation import UnavailableGenerator
    from case_intelligence.workbench import create_workbench_app
    from tests.test_source_folder_navigation import _register
    from tests.test_source_library import _matter
    app = create_workbench_app(tmp_path / 'runtime', generator=UnavailableGenerator(),
        auth_mode='test', background_ingestion=False)
    with TestClient(app) as client:
        matter = app.state.workbench.matter(_matter(client), ACTOR)
        bench = app.state.workbench
        documents = _register(bench, matter, [f'Batch {i // 100:03d}/row-{i:05d}.txt' for i in range(10_000)])
        store = bench.source_store(matter)
        # Generated catalog scale fixture only. Actual admission and byte hashing
        # are exercised by the real HTTP upload tests above.
        with store._lock:
            for d in documents.values():
                d.digest = 'b' * 64
            store._save()
        def forbidden(*_args, **_kwargs):
            raise AssertionError('Browsing must not read or hash the source inventory')
        store.source_path = forbidden
        bench._source_rows = forbidden
        # Count each identical-byte group once, not once per displayed source.
        # Bound VM work, rather than imposing a wall-clock deadline on CI hosts.
        query_steps = 0
        def query_budget():
            nonlocal query_steps
            query_steps += 1000
            return int(query_steps > 5_000_000)
        bench.workspace.connection.set_progress_handler(query_budget, 1000)
        try:
            filters = (
                {"matching_only": True} if filter_mode == "matching" else
                {"same_content": store.action_token(next(iter(documents.values())))}
                if filter_mode == "comparison" else {}
            )
            page = bench.source_library(matter, view='list', page_size=100, page=100, **filters)
        finally:
            bench.workspace.connection.set_progress_handler(None, 0)
        assert query_steps <= 5_000_000
        assert page.total == 10_000 and len(page.items) == 100
        assert all(row.byte_match_count == 10_000 for row in page.items)
        token = page.items[0].action_token
        compared = bench.source_library(matter, same_content=token, folder='Batch 099')
        assert compared.total == 100 and len(compared.items) == 50
        folders = bench.workspace.source_catalog_folders(matter.matter_id, same_content=token, offset=50)
        assert folders.total == 100 and len(folders.items) == 50
        assert all(f.source_count == 100 for f in folders.items)
        workspace = bench.workspace
        # Simulate an older writer changing only the catalog. Stale derived rows
        # must fail closed until normal registry reconciliation repairs them.
        with workspace._lock, workspace.connection:
            workspace.connection.execute('UPDATE workbench_source_catalog SET version_id=? WHERE matter_id=? AND action_token=?',
                ('e' * 32, matter.matter_id, token))
        assert bench.source_library(matter, same_content=token).total == 0
        projected = [bench._source_catalog_projection(d) for d in documents.values()]
        assert workspace.replace_source_catalog(matter.matter_id, projected) == 10_000
        assert bench.source_library(matter, same_content=token, page_size=25).total == 10_000
        selected = page.items[0].document_id
        assert workspace.delete_source_catalog(matter.matter_id, [selected]) == 1
        assert workspace.connection.execute('SELECT count(*) FROM workbench_source_byte_match WHERE matter_id=? AND document_id=?',
            (matter.matter_id, selected)).fetchone()[0] == 0


def test_unreceived_and_quarantined_intake_cannot_create_byte_matches(tmp_path):
    import hashlib
    from fastapi.testclient import TestClient
    from case_intelligence.generation import UnavailableGenerator
    from case_intelligence.workbench import create_workbench_app
    from tests.test_source_library import DetectedScanner, _matter
    app = create_workbench_app(tmp_path / 'runtime', generator=UnavailableGenerator(),
        auth_mode='test', background_ingestion=True, malware_scanner=DetectedScanner(),
        malware_scan_mode='extended')
    with TestClient(app) as client:
        slug = _matter(client, 'Generated blocked byte comparison')
        bench = app.state.workbench
        matter = bench.matter(slug, ACTOR)
        body = b'generated,detection\n'
        for _ in range(2):
            created = client.post(f'/matters/{slug}/upload-sessions', json={
                'collection_name': 'Generated blocked selection', 'files': [{
                    'name': 'generated.csv', 'relative_path': 'Records/generated.csv',
                    'size': len(body), 'media_type': 'text/csv',
                    'source_sha256': hashlib.sha256(body).hexdigest()}]}).json()
            item = created['items'][0]
            assert bench.source_library(matter, matching_only=True).total == 0
            put(client, item, body)
            assert client.post(item['finalize_url']).status_code == 422
        assert bench.source_store(matter).malware_scan_status()['quarantined'] == 2
        assert bench.source_library(matter).total == 0
        assert bench.workspace.connection.execute('SELECT count(*) FROM workbench_source_byte_match WHERE matter_id=?',
            (matter.matter_id,)).fetchone()[0] == 0


def test_bulk_group_success_and_recovery_keep_comparison_in_fixed_matter_route(workspace):
    from html import unescape
    from urllib.parse import parse_qs, urlsplit
    client, bench, matter = workspace
    documents = matched_sources(client, bench, matter)
    token = bench.source_store(matter).action_token(documents[0])
    page = client.get(f'/matters/{matter.slug}/setup', params={
        'view': 'list', 'same_content': token, 'matching_only': 'true', 'folder': 'Records'})
    return_query = unescape(re.search(r'name="return_query" value="([^"]*)"', page.text).group(1))
    root = f'/matters/{matter.slug}/sources/bulk'
    for action in ('create_set', 'unknown-action'):
        response = client.post(root, data={'selected': [bench.source_store(matter).action_token(d) for d in documents[:2]],
            'action': action, 'source_set_name': 'Generated matching source set',
            'return_query': return_query + '&next=https%3A%2F%2Fexample.test%2Fwrong'}, follow_redirects=False)
        assert response.status_code == 303
        url = urlsplit(response.headers['location'])
        assert not url.netloc and url.path == f'/matters/{matter.slug}/setup'
        query = parse_qs(url.query)
        assert query['same_content'] == [token] and query['folder'] == ['Records']
        assert 'next' not in query and query['matching_only'] == ['true']
        returned = client.get(response.headers['location'])
        assert returned.status_code == 200 and returned.text.count('class="source-table-row') == 2
    assert bench.workspace.source_sets(matter.matter_id)[0].source_count == 2
