"""Synthetic runner failures must not produce a green browser CI result."""
from __future__ import annotations

import hashlib
import importlib.util
import json
import os
from pathlib import Path
import signal
import stat
import subprocess
import sys
import time
import zipfile
from unittest.mock import Mock

import pytest

ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture
def runner():
    spec = importlib.util.spec_from_file_location('browser_acceptance_runner', ROOT / 'scripts/run-browser-acceptance.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def intake_script():
    spec = importlib.util.spec_from_file_location('browser_intake', ROOT / 'scripts/browser-accept-intake-receipts.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_refresh_waits_for_replacement_document_and_complete_load(intake_script):
    from selenium.common.exceptions import StaleElementReferenceException
    from selenium.webdriver.support.ui import WebDriverWait

    driver = Mock()
    previous = driver.find_element.return_value
    previous.is_enabled.side_effect = [True, StaleElementReferenceException()]
    driver.execute_script.side_effect = ['loading', 'complete']
    intake_script.refresh_page(driver, WebDriverWait(driver, 1, poll_frequency=.001))
    driver.refresh.assert_called_once_with()
    assert previous.is_enabled.call_count == 2
    assert driver.execute_script.call_count == 2


@pytest.mark.parametrize('stalled_document', ['old', 'new'])
def test_refresh_fails_when_navigation_does_not_finish(intake_script, stalled_document):
    from selenium.common.exceptions import StaleElementReferenceException, TimeoutException
    from selenium.webdriver.support.ui import WebDriverWait

    driver = Mock()
    if stalled_document == 'new':
        driver.find_element.return_value.is_enabled.side_effect = StaleElementReferenceException()
    driver.execute_script.return_value = 'loading'
    with pytest.raises(TimeoutException):
        intake_script.refresh_page(driver, WebDriverWait(driver, .01, poll_frequency=.001))
    if stalled_document == 'old':
        driver.execute_script.assert_not_called()


def receipt(path, **values):
    path.write_text(json.dumps({'passed': True, 'synthetic_only': True,
        'checks': ['Generated check'] * 12, **values}))


def test_pins_match_browser_driver_version_and_official_archives(runner):
    for name in ('linux64', 'mac-arm64'):
        version, pins = runner.browser_pins(name)
        assert set(pins) == {'chrome', 'chromedriver'}
        assert all(f'/{version}/{name}/' in pin['url'] for pin in pins.values())


def test_mismatched_download_is_rejected_before_extraction(runner, tmp_path, monkeypatch):
    archive = tmp_path / 'chrome-linux64.zip'
    archive.write_bytes(b'Generated corrupt browser download')
    monkeypatch.setattr(runner, 'browser_pins', lambda _: ('1.2.3.4', {
        'chrome': {'sha256': '0' * 64}, 'chromedriver': {'sha256': '0' * 64}}))
    monkeypatch.setattr(runner, 'extract_archive', lambda *_: pytest.fail('Unverified archive was extracted'))
    with pytest.raises(ValueError, match='SHA-256 mismatch'):
        runner.install_browser(tmp_path, 'linux64', tmp_path)


def test_archive_verification_also_applies_to_offline_copies(runner, tmp_path):
    archive = tmp_path / 'generated.zip'
    archive.write_bytes(b'Generated fixed archive bytes')
    runner.verify_archive(archive, hashlib.sha256(archive.read_bytes()).hexdigest())
    link = tmp_path / 'linked.zip'
    link.symlink_to(archive)
    with pytest.raises(ValueError, match='regular file'):
        runner.verify_archive(link, hashlib.sha256(archive.read_bytes()).hexdigest())


@pytest.mark.parametrize('name,target', [('../escaped', None), ('/escaped', None), ('link', '../../escaped')])
def test_archive_paths_cannot_escape_scratch(runner, tmp_path, name, target):
    archive = tmp_path / 'generated.zip'
    with zipfile.ZipFile(archive, 'w') as bundle:
        entry = zipfile.ZipInfo(name)
        entry.external_attr = ((stat.S_IFLNK | 0o777) if target else (stat.S_IFREG | 0o644)) << 16
        bundle.writestr(entry, target or 'Generated bytes')
    with pytest.raises(ValueError, match='Unsafe browser archive'):
        runner.extract_archive(archive, tmp_path / 'extracted')
    assert not (tmp_path / 'escaped').exists()


def test_safe_framework_links_and_executable_modes_are_preserved(runner, tmp_path):
    archive = tmp_path / 'generated.zip'
    with zipfile.ZipFile(archive, 'w') as bundle:
        entry = zipfile.ZipInfo('Versions/A/generated')
        entry.external_attr = (stat.S_IFREG | 0o755) << 16
        bundle.writestr(entry, 'Generated executable bytes')
        entry = zipfile.ZipInfo('Versions/Current')
        entry.external_attr = (stat.S_IFLNK | 0o777) << 16
        bundle.writestr(entry, 'A')
    root = tmp_path / 'extracted'
    runner.extract_archive(archive, root)
    assert (root / 'Versions/Current/generated').read_text() == 'Generated executable bytes'
    assert (root / 'Versions/A/generated').stat().st_mode & 0o111


@pytest.mark.parametrize('kind', ['missing', 'malformed', 'failed', 'not_synthetic', 'empty', 'truncated', 'symlink'])
def test_receipt_validation_fails_closed(runner, tmp_path, kind):
    path = tmp_path / 'receipt.json'
    if kind != 'missing':
        receipt(path)
    if kind == 'malformed':
        path.write_text('{')
    elif kind == 'failed':
        receipt(path, passed=False)
    elif kind == 'not_synthetic':
        receipt(path, synthetic_only=False)
    elif kind == 'empty':
        receipt(path, checks=[])
    elif kind == 'truncated':
        receipt(path, checks=['Generated incomplete check'])
    elif kind == 'symlink':
        source = tmp_path / 'real.json'
        path.rename(source)
        path.symlink_to(source)
    with pytest.raises((ValueError, OSError)):
        runner.check_receipt(path, 11)


def test_artifacts_are_bounded_allowlisted_and_exclude_runtime_and_downloads(runner, tmp_path, monkeypatch):
    raw = tmp_path / 'raw'
    raw.mkdir()
    receipt(raw / 'receipt.json')
    (raw / 'runtime.sqlite').write_text('Generated runtime')
    (raw / 'downloads').mkdir()
    (raw / 'downloads/final.zip').write_text('Generated bundle')
    (raw / 'failure.html').symlink_to(raw / 'runtime.sqlite')
    (raw / 'failure.png').write_bytes(b'x' * 1000)
    log = tmp_path / 'raw.log'
    log.write_bytes(b'x' * 2000)
    monkeypatch.setattr(runner, 'MAX_FILE_BYTES', 500)
    monkeypatch.setattr(runner, 'MAX_LOG_BYTES', 100)
    output = tmp_path / 'output'
    remaining, omitted = runner.collect_artifacts(raw, output, log, 900)
    assert set(path.name for path in output.iterdir()) == {'receipt.json', 'journey.log'}
    assert set(omitted) == {'failure.html', 'failure.png'}
    assert (output / 'journey.log').stat().st_size == 100
    assert sum(path.stat().st_size for path in output.iterdir()) == 900 - remaining


def test_environment_excludes_deployment_and_proxy_settings(runner, tmp_path, monkeypatch):
    for key in ('CASE_INTELLIGENCE_POSTGRES_DSN', 'DATABASE_URL', 'HTTP_PROXY', 'HTTPS_PROXY', 'PYTHONHOME'):
        monkeypatch.setenv(key, 'generated-untrusted-value')
    env = runner.child_environment(tmp_path)
    assert all(value != 'generated-untrusted-value' for value in env.values())
    assert env['HF_HUB_OFFLINE'] == env['TRANSFORMERS_OFFLINE'] == '1'
    assert env['CASE_INTELLIGENCE_STORAGE_RESERVE_GIB'] == '0'
    assert Path(env['TMPDIR']).is_dir()


def test_existing_output_is_preserved_and_no_journey_runs(runner, tmp_path, monkeypatch):
    output = tmp_path / 'old'
    output.mkdir()
    marker = output / 'summary.json'
    marker.write_text('Generated old result')
    monkeypatch.setattr(runner, 'install_browser', lambda *_: pytest.fail('Browser ran with stale output'))
    assert runner.main(['--output', str(output)]) == 1
    assert marker.read_text() == 'Generated old result'


@pytest.mark.parametrize('failure', ['exit', 'timeout', 'missing', 'failed', 'none'])
def test_both_journeys_run_and_failure_cannot_be_hidden_by_receipt(runner, tmp_path, monkeypatch, failure):
    scratch, output = tmp_path / 'scratch', tmp_path / 'output'
    scratch.mkdir()
    output.mkdir()
    commands = []

    def run(command, log, environment, timeout):
        commands.append(command)
        raw = Path(command[command.index('--output') + 1])
        log.write_text('Generated child output')
        name = 'receipt-browser-result.json' if len(commands) == 1 else 'receipt.json'
        if failure != 'missing' or len(commands) != 1:
            receipt(raw / name, passed=failure != 'failed' or len(commands) != 1)
        if len(commands) == 1:
            if failure == 'exit':
                return 9  # A success receipt must not mask a process error.
            if failure == 'timeout':
                raise subprocess.TimeoutExpired(command, timeout)
        return 0

    monkeypatch.setattr(runner, 'run_process', run)
    results = runner.run_journeys(Path('/generated/chrome'), Path('/generated/driver'), scratch, output, 1)
    assert len(commands) == 2
    assert '--verify-readiness' in commands[1]
    assert results[0]['passed'] is (failure == 'none')
    assert results[1]['passed'] is True
    assert json.loads((output / 'journeys.json').read_text()) == results


def alive(pid):
    state = subprocess.run(['ps', '-o', 'stat=', '-p', str(pid)], capture_output=True, text=True).stdout.strip()
    return bool(state) and not state.startswith('Z')


@pytest.mark.parametrize('leader_exits', [True, False])
def test_process_group_cleanup_includes_orphan_descendants(runner, tmp_path, leader_exits):
    marker = tmp_path / 'pid'
    code = """
import os, pathlib, signal, subprocess, sys, time
child = subprocess.Popen([sys.executable, '-c', 'import signal,time;signal.signal(signal.SIGTERM,signal.SIG_IGN);time.sleep(60)'])
pathlib.Path(sys.argv[1]).write_text(str(child.pid))
if sys.argv[2] == 'wait':
    time.sleep(60)
"""
    command = [sys.executable, '-c', code, str(marker), 'exit' if leader_exits else 'wait']
    if leader_exits:
        assert runner.run_process(command, tmp_path / 'log', dict(os.environ), 3) == 0
    else:
        with pytest.raises(subprocess.TimeoutExpired):
            runner.run_process(command, tmp_path / 'log', dict(os.environ), 1)
    child = int(marker.read_text())
    deadline = time.monotonic() + 3
    while alive(child) and time.monotonic() < deadline:
        time.sleep(.05)
    assert not alive(child), 'Generated descendant survived process-group cleanup'


def test_sigterm_interrupt_cleans_active_child_and_returns_failure(runner, tmp_path):
    marker = tmp_path / 'started'
    code = """
import importlib.util, os, pathlib, signal, sys
spec=importlib.util.spec_from_file_location('runner', sys.argv[1]);r=importlib.util.module_from_spec(spec);spec.loader.exec_module(r)
signal.signal(signal.SIGTERM, r.interrupted)
try:
    r.run_process([sys.executable, '-c', 'import os,pathlib,sys,time;pathlib.Path(sys.argv[1]).write_text(str(os.getpid()));time.sleep(60)', sys.argv[2]], pathlib.Path(sys.argv[3]), dict(os.environ), 30)
except InterruptedError:
    sys.exit(17)
"""
    parent = subprocess.Popen([sys.executable, '-c', code, str(ROOT / 'scripts/run-browser-acceptance.py'),
        str(marker), str(tmp_path / 'log')])
    try:
        deadline = time.monotonic() + 5
        while not marker.exists() and time.monotonic() < deadline:
            time.sleep(.02)
        assert marker.exists()
        parent.send_signal(signal.SIGTERM)
        assert parent.wait(timeout=5) == 17
        assert not alive(int(marker.read_text()))
    finally:
        if parent.poll() is None:
            parent.kill()
        parent.wait()


@pytest.mark.parametrize('kind', ['good', 'oversized', 'redirected'])
def test_download_is_bounded_and_stays_on_pinned_url(runner, tmp_path, monkeypatch, kind):
    import io
    url = 'https://storage.googleapis.com/chrome-for-testing-public/1.2.3.4/linux64/chrome-linux64.zip'
    class Response(io.BytesIO):
        def geturl(self):
            return url if kind != 'redirected' else 'https://example.test/unexpected'
    monkeypatch.setattr(runner.urllib.request, 'urlopen', lambda *a, **kw: Response(b'Generated archive'))
    monkeypatch.setattr(runner, 'MAX_ARCHIVE_BYTES', 2 if kind == 'oversized' else 100)
    if kind == 'good':
        runner.download_archive(url, tmp_path / 'archive.zip')
        assert (tmp_path / 'archive.zip').read_bytes() == b'Generated archive'
    else:
        with pytest.raises(ValueError, match='limit|redirect'):
            runner.download_archive(url, tmp_path / 'archive.zip')


def test_mismatched_driver_version_pin_is_rejected(runner, tmp_path, monkeypatch):
    manifest = json.loads((ROOT / 'config/browser-testing.json').read_text())
    manifest['platforms']['linux64']['chromedriver']['url'] = manifest['platforms']['linux64']['chromedriver']['url'].replace(manifest['version'], '1.2.3.4')
    (tmp_path / 'config').mkdir()
    (tmp_path / 'config/browser-testing.json').write_text(json.dumps(manifest))
    monkeypatch.setattr(runner, 'ROOT', tmp_path)
    with pytest.raises(ValueError, match='matching immutable'):
        runner.browser_pins('linux64')


@pytest.mark.parametrize('outcomes,code', [([True, False], 1), ([True, True], 0), ([], 1)])
def test_main_requires_both_journeys_to_pass(runner, tmp_path, monkeypatch, outcomes, code):
    monkeypatch.setattr(runner, 'install_browser', lambda *_: (Path('/generated/chrome'), Path('/generated/driver'), '1.2.3.4'))
    monkeypatch.setattr(runner, 'host_platform', lambda: 'linux64')
    monkeypatch.setattr(runner, 'run_journeys', lambda *_: [{'passed': passed} for passed in outcomes])
    output = tmp_path / 'output'
    assert runner.main(['--output', str(output)]) == code
    assert json.loads((output / 'summary.json').read_text())['passed'] is (code == 0)
