#!/usr/bin/env python3
"""Stopped previous-reader compatibility and forward reconstruction of byte matches."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))
from fastapi.testclient import TestClient  # noqa: E402
from case_intelligence.generation import UnavailableGenerator  # noqa: E402
from case_intelligence.workbench import create_workbench_app  # noqa: E402

ACTOR = 'development-taylor-morgan'
BODY = b'Generated identical source reader fixture.\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--previous-source', type=Path, required=True)
    args = parser.parse_args()
    previous = args.previous_source.resolve()
    if not (previous / 'src/case_intelligence/workspace_store.py').is_file():
        raise SystemExit('Choose the previous source checkout.')
    with tempfile.TemporaryDirectory(prefix='recordbench-byte-match-reader-') as temporary:
        root = Path(temporary)
        runtime = root / 'runtime'
        with TestClient(create_workbench_app(runtime, generator=UnavailableGenerator(),
                auth_mode='test', background_ingestion=False)) as client:
            response = client.post('/matters', data={'name': 'Generated byte match reader'}, follow_redirects=False)
            slug = response.headers['location'].split('/')[2]
            bench = client.app.state.workbench
            matter = bench.matter(slug, ACTOR)
            store = bench.source_store(matter)
            expected = []
            for character in ('a', 'b'):
                item = 'upload-item-' + character * 32
                store.append_resumable_chunk(item, offset=0, expected_size=len(BODY), chunk=BODY)
                document = store.finalize_resumable_upload(item, display_name='report.txt',
                    relative_path='Records/report.txt', content_type='text/plain', expected_size=len(BODY))
                expected.append([document.document_id, document.version_id, document.digest, document.size])
            token = store.action_token(document)
            assert bench.source_library(matter, same_content=token).total == 2
        (root / 'expected.json').write_text(json.dumps({'slug': slug, 'sources': expected}))
        code = '''
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(sys.argv[1])/'src'))
from fastapi.testclient import TestClient
from case_intelligence.generation import UnavailableGenerator
from case_intelligence.workbench import create_workbench_app
root=Path(sys.argv[2]); expected=json.loads((root/'expected.json').read_text())
with TestClient(create_workbench_app(root/'runtime',generator=UnavailableGenerator(),auth_mode='test',background_ingestion=False)) as client:
    bench=client.app.state.workbench
    matter=bench.matter(expected['slug'],'development-taylor-morgan')
    page=client.get('/matters/'+matter.slug+'/setup?view=list')
    assert page.status_code==200 and page.text.count('class="source-table-row')==2
    store=bench.source_store(matter)
    for identity,version,digest,size in expected['sources']:
        document=store.get(identity)
        assert [document.document_id,document.version_id,document.digest,document.size]==[identity,version,digest,size]
        assert store.source_path(identity).read_bytes()==b'Generated identical source reader fixture.\\n'
    # Older catalog decoding and export selection must both tolerate the new
    # derived table without adding fields to the old catalog or registry JSON.
    assert len(bench.workspace.source_catalog_for_export(matter.matter_id,'development-taylor-morgan'))==2
print('Previous Sources and export readers preserve both exact received versions.')
'''
        subprocess.run([sys.executable, '-c', code, str(previous), str(root)], check=True)
        with TestClient(create_workbench_app(runtime, generator=UnavailableGenerator(),
                auth_mode='test', background_ingestion=False)) as client:
            bench = client.app.state.workbench
            matter = bench.matter(slug, ACTOR)
            store = bench.source_store(matter)
            assert bench.source_library(matter, same_content=token).total == 2
            assert all(item.byte_match_count == 2 for item in bench.source_library(matter).items)
            assert len(store.documents) == 2
            assert all(store.source_path(identity).read_bytes() == BODY for identity, *_ in expected)
        print('Forward opening restores identical-byte comparison without changing source identities or bytes.')


if __name__ == '__main__':
    main()
